import react from '@vitejs/plugin-react'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitest/config'

const alias = {
  '@': fileURLToPath(new URL('src', import.meta.url)),
  '~tests': fileURLToPath(new URL('tests', import.meta.url)),
}

export default defineConfig({
  test: {
    coverage: {
      // Only code we author and that carries logic. Wiring (`app/`, `routes/`),
      // vendored shadcn components and generated output are covered by the
      // Playwright acceptance suite instead; see docs/qa/quality-metrics.md.
      exclude: [
        '**/*.test.{ts,tsx}',
        // Generated by the shadcn CLI; the same files the ESLint config lists
        // as vendored. Components we author in shared/ui are measured.
        'src/shared/ui/button.tsx',
        'src/shared/ui/card.tsx',
        'src/shared/ui/input.tsx',
        'src/shared/ui/label.tsx',
      ],
      include: [
        'src/entities/**/*.{ts,tsx}',
        'src/features/**/*.{ts,tsx}',
        'src/widgets/**/*.{ts,tsx}',
        'src/pages/**/*.{ts,tsx}',
        'src/shared/i18n/**/*.tsx',
        'src/shared/lib/**/*.ts',
        'src/shared/ui/**/*.tsx',
      ],
      // istanbul instruments the source instead of merging V8 range trees,
      // whose merge step overflows the stack on a suite this size.
      provider: 'istanbul',
      reporter: ['text', 'html', 'lcov', 'cobertura'],
      reportsDirectory: './coverage',
      thresholds: {
        branches: 90,
        functions: 90,
        lines: 90,
        // The model layer is pure and cheap to test, so it carries no excuses.
        'src/**/model/**': {
          branches: 100,
          functions: 100,
          lines: 100,
          statements: 100,
        },
        statements: 90,
      },
    },

    projects: [
      {
        // Pure business rules: no DOM, no network, no React.
        resolve: { alias },
        test: {
          environment: 'node',
          include: ['src/**/model/**/*.test.ts', 'tests/domain/**/*.test.ts'],
          name: 'domain',
        },
      },
      {
        // Components and hooks against a DOM, with GitLab's API mocked by MSW.
        plugins: [react()],
        resolve: { alias },
        test: {
          environment: 'happy-dom',
          exclude: ['src/**/model/**'],
          include: ['src/**/*.test.tsx', 'src/**/*.test.ts', 'tests/ui/**/*.test.tsx'],
          /**
           * One environment per worker rather than one per file.
           *
           * Measured on this suite: 28 seconds to 12, and coverage from 60 to
           * 39, because most of the cost was never the assertions — it was
           * importing the module graph and building a DOM 62 times over.
           *
           * What it trades away is isolation between files in the same worker,
           * so the three ways state could cross that boundary were each probed
           * rather than assumed. Spies do NOT leak: Vitest restores them when a
           * file ends, verified with an unrestored `vi.spyOn(console, 'error')`.
           * Storage does NOT leak: the `afterEach` in `tests/setup/ui.ts` clears
           * it, and that is also what keeps Paraglide's cached locale from
           * carrying a language into the next file. Module scope DOES leak — a
           * value written to `globalThis` in one file was read in the next.
           *
           * Which is survivable here for a structural reason rather than a lucky
           * one: the tested slices hold no mutable module state (two Intl caches
           * keyed by locale, one frozen Set), and the singletons that would be
           * dangerous — the query client, its persister, the app runtime — live
           * in `src/app/`, which has no tests and which no tested slice may
           * import, because the FSD boundary rule forbids importing the top
           * layer. If that ever changes, this line is what makes it a bug.
           */
          isolate: false,
          name: 'ui',
          setupFiles: ['./tests/setup/ui.ts'],
        },
      },
    ],
  },
})
