import react from '@vitejs/plugin-react'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitest/config'

const alias = {
  '@': fileURLToPath(new URL('src', import.meta.url)),
  '~tests': fileURLToPath(new URL('tests', import.meta.url)),
}

export default defineConfig({
  test: {
    coverage: {
      // Only code we author and that carries logic. Wiring (`app/`, `routes/`),
      // vendored shadcn components and generated output are covered by the
      // Playwright acceptance suite instead; see docs/qa/quality-metrics.md.
      exclude: [
        '**/*.test.{ts,tsx}',
        // Generated by the shadcn CLI; the same files the ESLint config lists
        // as vendored. Components we author in shared/ui are measured.
        'src/shared/ui/button.tsx',
        'src/shared/ui/card.tsx',
        'src/shared/ui/input.tsx',
        'src/shared/ui/label.tsx',
      ],
      include: [
        // The function is authored here and carries logic, so it is measured.
        // It is not `model/`, so it is held to the global floor rather than the
        // hundred-percent one: its handler is I/O wiring.
        'netlify/**/*.mts',
        'src/entities/**/*.{ts,tsx}',
        'src/features/**/*.{ts,tsx}',
        'src/widgets/**/*.{ts,tsx}',
        'src/pages/**/*.{ts,tsx}',
        'src/shared/i18n/**/*.tsx',
        'src/shared/lib/**/*.ts',
        'src/shared/ui/**/*.tsx',
      ],
      // istanbul instruments the source instead of merging V8 range trees,
      // whose merge step overflows the stack on a suite this size.
      provider: 'istanbul',
      reporter: ['text', 'html', 'lcov', 'cobertura'],
      reportsDirectory: './coverage',
      thresholds: {
        branches: 90,
        functions: 90,
        lines: 90,
        // The model layer is pure and cheap to test, so it carries no excuses.
        'src/**/model/**': {
          branches: 100,
          functions: 100,
          lines: 100,
          statements: 100,
        },
        /**
         * The one place seconds become hours. It is model code by nature and
         * carries the model floor; it sits in shared only because two entity
         * slices need it and FSD forbids one reaching into the other.
         */
        'src/shared/lib/duration.ts': {
          branches: 100,
          functions: 100,
          lines: 100,
          statements: 100,
        },
        /**
         * Model code outside a `model/` directory for the same reason: the
         * report orders the rows it drew and the team editor orders the list
         * the reader is building, and FSD forbids one slice reaching into the
         * other. Deterministic row order is a spec requirement, not a nicety.
         */
        'src/shared/lib/people.ts': {
          branches: 100,
          functions: 100,
          lines: 100,
          statements: 100,
        },
        statements: 90,
      },
    },

    projects: [
      {
        /**
         * Pure business rules: no DOM, no network, no React.
         *
         * `shared/lib/duration.ts` is named explicitly because it is model code
         * that lives outside a `model/` directory — two entity slices need it
         * and FSD forbids one reaching into the other. Left to the glob it
         * would run in the `ui` project instead, and Stryker’s per-test
         * coverage would stop associating its mutants with the tests that kill
         * them: the mutation score on the one place seconds become hours would
         * quietly drop.
         */
        resolve: { alias },
        test: {
          environment: 'node',
          include: [
            'src/**/model/**/*.test.ts',
            'src/shared/lib/duration.test.ts',
            'src/shared/lib/people.test.ts',
            'tests/domain/**/*.test.ts',
          ],
          name: 'domain',
        },
      },
      {
        /**
         * The serverless function: Node, no DOM, no React — and no Netlify.
         *
         * The blob store and the identity verifier are ports, so these tests
         * inject an in-memory store and a locally minted key pair rather than
         * reaching for `getStore`, which throws outside a Netlify environment.
         * That is also what makes the credential rules testable at all: the
         * acceptance suite serves a static build and has no function in it.
         *
         * The alias is shared with the other two projects for the contract
         * tests: `{teams,preferences}-contract.test.mts` import the browser's
         * lenient codec and run it beside the endpoint's strict validator, which
         * is the only way the two halves of one stored shape can be held against
         * each other. They live in different layers and different runtimes, so
         * nothing else makes them meet.
         */
        resolve: { alias },
        test: {
          environment: 'node',
          include: ['netlify/**/*.test.mts'],
          name: 'functions',
        },
      },
      {
        // Components and hooks against a DOM, with GitLab's API mocked by MSW.
        plugins: [react()],
        resolve: { alias },
        test: {
          environment: 'happy-dom',
          exclude: [
            'src/**/model/**',
            'src/shared/lib/duration.test.ts',
            'src/shared/lib/people.test.ts',
          ],
          include: ['src/**/*.test.tsx', 'src/**/*.test.ts', 'tests/ui/**/*.test.tsx'],
          /**
           * One environment per worker rather than one per file.
           *
           * Measured on this suite: 28 seconds to 12, and coverage from 60 to
           * 39, because most of the cost was never the assertions — it was
           * importing the module graph and building a DOM 62 times over.
           *
           * What it trades away is isolation between files in the same worker,
           * so the three ways state could cross that boundary were each probed
           * rather than assumed. Spies do NOT leak: Vitest restores them when a
           * file ends, verified with an unrestored `vi.spyOn(console, 'error')`.
           * Storage does NOT leak: the `afterEach` in `tests/setup/ui.ts` clears
           * it, and that is also what keeps Paraglide's cached locale from
           * carrying a language into the next file. Module scope DOES leak — a
           * value written to `globalThis` in one file was read in the next.
           *
           * Which is survivable here for a structural reason rather than a lucky
           * one: the tested slices hold no mutable module state (two Intl caches
           * keyed by locale, one frozen Set), and the singletons that would be
           * dangerous — the query client, its persister, the app runtime — live
           * in `src/app/`, which has no tests and which no tested slice may
           * import, because the FSD boundary rule forbids importing the top
           * layer. If that ever changes, this line is what makes it a bug.
           */
          isolate: false,
          name: 'ui',
          setupFiles: ['./tests/setup/ui.ts'],
        },
      },
    ],
  },
})
